import { forwardRef } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import ViewShot from 'react-native-view-shot';
import { colorTokens, spacingTokens, radiusTokens } from '../theme/tokens';
import { typographyTokens } from '../theme/typography';

export type ShareableSettlementListModel = {
  currency: string;
  recommendations: Array<{
    fromLabel: string;
    toLabel: string;
    amountLabel: string;
  }>;
};

export const ShareableSettlementList = forwardRef<ViewShot, { model: ShareableSettlementListModel }>(
  ({ model }, ref) => {
    return (
      <ViewShot ref={ref} options={{ format: 'png', quality: 0.9 }}>
        <View style={styles.container}>
          <View style={styles.header}>
            <Text style={styles.title}>Settlement Summary</Text>
            <Text style={styles.subtitle}>Currency: {model.currency}</Text>
          </View>

          {model.recommendations.length === 0 ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyHeading}>No transfers needed</Text>
              <Text style={styles.emptyBody}>Everyone is currently balanced for the selected currency.</Text>
            </View>
          ) : (
            <View style={styles.list}>
              {model.recommendations.map((entry, index) => (
                <View key={`${entry.fromLabel}-${entry.toLabel}-${index}`} style={styles.row}>
                  <Text style={styles.route}>{entry.fromLabel} → {entry.toLabel}</Text>
                  <Text style={styles.amount}>{entry.amountLabel}</Text>
                </View>
              ))}
            </View>
          )}

          <View style={styles.footer}>
            <Text style={styles.footerText}>Generated by Dumshare</Text>
          </View>
        </View>
      </ViewShot>
    );
  },
);

ShareableSettlementList.displayName = 'ShareableSettlementList';

const styles = StyleSheet.create({
  container: {
    backgroundColor: colorTokens.appBackground,
    padding: spacingTokens.lg,
    gap: spacingTokens.md,
  },
  header: {
    gap: spacingTokens.xs,
  },
  title: {
    ...typographyTokens.heading,
    fontSize: 20,
  },
  subtitle: {
    fontSize: 14,
    color: colorTokens.textMuted,
  },
  list: {
    gap: spacingTokens.sm,
  },
  row: {
    padding: spacingTokens.md,
    borderRadius: radiusTokens.md,
    borderWidth: 1,
    borderColor: colorTokens.border,
    backgroundColor: colorTokens.card,
    gap: 4,
  },
  route: {
    fontSize: 15,
    color: colorTokens.textPrimary,
    fontWeight: '600',
  },
  amount: {
    color: colorTokens.textMuted,
  },
  emptyState: {
    borderRadius: radiusTokens.md,
    padding: 14,
    backgroundColor: colorTokens.card,
    borderWidth: 1,
    borderColor: colorTokens.border,
    gap: 6,
  },
  emptyHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: colorTokens.textPrimary,
  },
  emptyBody: {
    color: colorTokens.textMuted,
  },
  footer: {
    marginTop: spacingTokens.md,
    paddingTop: spacingTokens.md,
    borderTopWidth: 1,
    borderTopColor: colorTokens.border,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: colorTokens.textMuted,
  },
});
