import { forwardRef } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import ViewShot from 'react-native-view-shot';
import { colorTokens, spacingTokens } from '../theme/tokens';
import { typographyTokens } from '../theme/typography';
import { SettlementEmptyState, SettlementRow } from './SettlementBlocks';

export type ShareableSettlementListModel = {
  currency: string;
  recommendations: Array<{
    fromLabel: string;
    toLabel: string;
    amountLabel: string;
  }>;
};

export const ShareableSettlementList = forwardRef<ViewShot, { model: ShareableSettlementListModel }>(
  ({ model }, ref) => {
    return (
      <ViewShot ref={ref} options={{ format: 'png', quality: 0.9 }}>
        <View style={styles.container}>
          <View style={styles.header}>
            <Text style={styles.title}>Settlement Summary</Text>
            <Text style={styles.subtitle}>Currency: {model.currency}</Text>
          </View>

          {model.recommendations.length === 0 ? (
            <SettlementEmptyState />
          ) : (
            <View style={styles.list}>
              {model.recommendations.map((entry, index) => (
                <View key={`${entry.fromLabel}-${entry.toLabel}-${index}`}>
                  <SettlementRow fromLabel={entry.fromLabel} toLabel={entry.toLabel} amount={entry.amountLabel} />
                </View>
              ))}
            </View>
          )}

          <View style={styles.footer}>
            <Text style={styles.footerText}>Generated by Dumshare</Text>
          </View>
        </View>
      </ViewShot>
    );
  },
);

ShareableSettlementList.displayName = 'ShareableSettlementList';

const styles = StyleSheet.create({
  container: {
    backgroundColor: colorTokens.appBackground,
    padding: spacingTokens.lg,
    gap: spacingTokens.md,
  },
  header: {
    gap: spacingTokens.xs,
  },
  title: {
    ...typographyTokens.heading,
    fontSize: 20,
  },
  subtitle: {
    fontSize: 14,
    color: colorTokens.textMuted,
  },
  list: {
    gap: spacingTokens.sm,
  },
  footer: {
    marginTop: spacingTokens.md,
    paddingTop: spacingTokens.md,
    borderTopWidth: 1,
    borderTopColor: colorTokens.border,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: colorTokens.textMuted,
  },
});
